### ISSUE TITLE
Quick question - persistence

### ISSUE THREAD

**Issue by hypergig** [podraven/y-fire#1]
This provider looks great, exactly what I was looking for. 

I was wondering, if a user closes the tab before the persistent sync happens to firestore, would that data get lost? I know it's only what happened since the last sync (3000 ms default), but it would still get lost? Or is there a local / offline cache that remains behind?

**Comment by deathg0d** [comment]
True, we are working on the stable cache feature. In the meantime the provider offers the `onSaving` event so that you could alert the user. I apologize that this is not optimum. The cache feature is going to take a bit of work that's all.

**Comment by mitoyouhei** [comment]
I think y-indexeddb should be the one to use for local cache. I'm new to yjs, but I think that's the solution. Bind multiple provider together.

I'm still working on this, not sure how to implement it. It's just an idea. Will provide more info once I found more

**Comment by deathg0d** [comment]
We are working on incorporating cache (with IndexedDB) into the extension :) It's taking a little time to cover all bases (login/logout scenarios, for example)

**Comment by deathg0d** [comment]
We finally have a new update. 🎉 Version 2.0.0 includes local cache based on indexedDB. If the provider is abruptly destroyed, data persists on local cache, which is synced on reconnect. Release notes [here](https://github.com/podraven/y-fire/releases/tag/v2.0.0).
