### ISSUE TITLE
Firestore doc structure cannot be customized

### ISSUE THREAD

**Issue by mitoyouhei** [podraven/y-fire#4]
Inside function saveToFirestore, I can see we save the doc in a content property. And pass `{ merge: true }` to make sure it's not cover any other properties.
```
saveToFirestore = () => {
    try {
      // current document to firestore
      const ref = doc(this.db, this.documentPath);
      setDoc(
        ref,
        { content: Bytes.fromUint8Array(Y.encodeStateAsUpdate(this.doc)) },
        { merge: true }
      );
    } catch (error) {
      this.consoleHandler("error saving to firestore", error);
    } finally {
      if (this.onSaving) this.onSaving(false);
    }
  };
```

But in my case, my doc looks like this:
```
{
  name: "",
  createdAt: "",
  file: {
    fileContent,
    fileType: "some type"
  }
}
```
So is it possible to add a delegate setDoc function into FireProvider

```
new FireProvider({
    firebaseApp,
    ydoc,
    path: documentPath,
    setDocDelegator: asyc (ref, bytes) => {
      return await setDoc(
        ref,
        {
          name: "myFileName",
          createdAt: "20241231"
          file: {
            fileContent: bytes,
            fileType: "some type"
          }
        },
        { merge: true }
      );
    }
  });
```

And the saveToFirestore will be looks like this:
```
constructor({..., setDocDelegator}) {
    this.setDocDelegator = setDocDelegator ? setDocDelegator : (ref, bytes) => {
      setDoc(
        ref,
        { content: bytes  }
        { merge: true }
      );
    } 
}
saveToFirestore = () => {
    try {
      // current document to firestore
      const ref = doc(this.db, this.documentPath);
      this.setDocDelegator(ref, Bytes.fromUint8Array(Y.encodeStateAsUpdate(this.doc)))
    } catch (error) {
      this.consoleHandler("error saving to firestore", error);
    } finally {
      if (this.onSaving) this.onSaving(false);
    }
  };
```

I really need this ability, if you feel OK with it, I can create a PR to update it. If you want some other solution to solve this problem, let me know, I can code it.

**Comment by deathg0d** [comment]
Let us think about it a bit. I like the idea that you should be able to write to a custom field. The only drawback I see with your solution is that you are essentially sending all fields on every sync. Right? This one:

```
{
  name: "",
  createdAt: "",
  file: {
    fileContent,
    fileType: "some type"
  }
}
```
I feel like this is too easy to misuse by a beginner. Although this module can also create documents, I would recommend that the documents (with other fields) are created separately, and only one field (ex: content) is managed by the plugin.

**Comment by mitoyouhei** [comment]
Yes, you are right. My solution is not a good one. My main require is custom field. Actually not just content field, the instancs collection name as well. In my case, I prefer use something like yjs-client. But I can't change. 

More things, when update content, I also want to update field updatedAt feild, which is the oen I record the latest update time. My app need that time to do the sort.

And I want you know, I found these requirement is not a short work, I really appreciate the work that have beed done, and I love to contribute if you OK. You can tell me your solution, and I can code for it. It's totally fine for me. I don't want to be a guy who just ask but not contribute. :)

**Comment by deathg0d** [comment]
I have created a pull request https://github.com/podraven/y-fire/pull/6. I think it should solve your use case right?

**Comment by deathg0d** [comment]
Fixed with https://github.com/podraven/y-fire/releases/tag/v2.1.1. I am closing this issue. If there are further issues, we can open it again.
